version: '3'
services:
  pgadmin:
    ports:
      - '5050:80'
  proxy:
    ports:
      - '80:80'
      - '8080:8080'
  flower:
    ports:
      - '5555:5555'
  backend:
    ports:
      - '8888:8888'
