version: '3'
services:
  db:
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: asd123Q
      PGDATA: /var/lib/postgresql/data/pgdata
  backend:
    environment:
      - SERVER_NAME=${DOMAIN}
      - SECRET_KEY=0c3a0e69406a6f671b94f1f72baf8e4d3a3ecd3f0c3e9a81557b0e245a7051a4
      - SENTRY_DSN=
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - FIRST_SUPERUSER=admin@adds-scraper.com
      - FIRST_SUPERUSER_PASSWORD=asd123Q
      - USERS_OPEN_REGISTRATION=${USERS_OPEN_REGISTRATION}
  celeryworker:
    environment:
      - SENTRY_DSN=
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - FIRST_SUPERUSER=admin@adds-scraper.com
      - FIRST_SUPERUSER_PASSWORD=asd123Q
      - USERS_OPEN_REGISTRATION=${USERS_OPEN_REGISTRATION}
