version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - DEFAULT_USER=admin@adds-scraper.com
      - DEFAULT_PASSWORD=asd123Q
      - PGADMIN_DEFAULT_EMAIL=admin@adds-scraper.com
      - PGADMIN_DEFAULT_PASSWORD=asd123Q
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=https://${DOMAIN}/api/v1/swagger/
  proxy:
    image: traefik:v1.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  flower:
    image: totem/celery-flower-docker
    environment:
      - FLOWER_BASIC_AUTH=root:asd123Q
      - AMQP_HOST=queue
      - AMQP_PORT=5672
